version: "3.8"
services:

    db:
        image: mysql
        container_name: test_db_symfony
        restart: always
        volumes:
            - db-data:/var/lib/mysql
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        networks:
            - dev

    phpmyadmin:
        image: phpmyadmin
        container_name: test_phpmyadmin_symfony
        restart: always
        depends_on:
            - db
        ports:
            - 8080:80
        environment:
            PMA_HOST: db
        networks:
            - dev

    www:
        build: docker/php
        container_name: test_symfony
        ports:
          - "8741:80"
        volumes:
            - ./docker/php/vhosts:/etc/apache2/sites-enabled
            - ./:/var/www
        restart: always
        networks:
            - dev

    rabbitmq:
        container_name: test_rabbitmq
        build:
          context: './docker/services/rabbitmq'
          args:
            VERSION: 3.7.10
        networks:
          - dev
        expose:
          - "5672"
        ports:
          - "15672:15672"
        volumes:
          - ./storage/data/rabbitmq:/var/lib/rabbitmq/mnesia

networks:
    dev:

volumes:
    db-data:
